//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JML_Traders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class af458_appointments
    {
        public int id { get; set; }
        public System.DateTime dateHour { get; set; }
        public string subject { get; set; }
        public int id_af458_brokers { get; set; }
        public int id_af458_customers { get; set; }
    
        public virtual af458_brokers af458_brokers { get; set; }
        public virtual af458_customers af458_customers { get; set; }
    }
}
